conditional supervisor kill

diff --git a/build/bin/supervisord-kill b/build/bin/supervisord-kill
--- a/build/bin/supervisord-kill
+++ b/build/bin/supervisord-kill
@@ -1,10 +1,31 @@
 #!/bin/bash
-############################################################################
-# Kill the supervisord process with the pid-file: /var/run/supervisord.pid #
-#--------------------------------------------------------------------------#
-# Maintainer: Mads Broen Nielsen                                           #
-############################################################################
+#########################################################################################
+# Kill the supervisord process with the pid-file: /var/run/supervisord.pid              #
+# Kill the process on if the results of the command provided equals the expected result #
+#---------------------------------------------------------------------------------------#
+# Maintainer: Mads Broen Nielsen                                                        #
+# TODO: Add usage information                                                           #
+#########################################################################################
 
 set -e
 
-kill -QUIT `cat /var/run/supervisord.pid`
+pid=/var/run/supervisord.pid
+
+while getopts ":c:e:" opt; do
+  case $opt in
+  c) cmd="$OPTARG"
+    ;;
+  e) expected="$OPTARG"
+    ;;
+  \?) echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
+done
+
+if [ ! -z "$cmd" ] && [ ! -z "$expected" ]; then
+  if [ ! `eval " $cmd"` == "$expected" ]; then
+    exit 0
+  fi
+fi
+
+[ -f $pid ] && kill -QUIT `cat $pid` || exit 1
